describe( 'Add Show', () => {
    it ( 'passes', () => {
        cy.visit( 'https://localhost:44492/Beheer' )
        cy.wait( 1000 )
        cy.get( 'button[id="addShow"]' ).click()
        cy.get('#startDateTime').type('2024-01-01T20:00:00')
        cy.get('#endDateTime').type('2024-01-01T22:00:00')
        cy.get('#voorstelling')
            .parent()
            .click()
            .get('ul > li[data-value="1"]')
            .click()
        cy.get('#zaalType')
            .parent()
            .click()
            .get('ul > li[data-value="Zaal_1"]')
            .click()
        //cy.get('button[id="addShow"]').click()
        cy.visit( 'https://localhost:44492/Programmering' )
    })
})